import { Grid } from 'nami'

render(
    <div>
        <Grid>
            <Grid.Col>24</Grid.Col>
        </Grid>
        <Grid>
            <Grid.Col>12</Grid.Col>
            <Grid.Col>12</Grid.Col>
        </Grid>
        <Grid>
            <Grid.Col>8</Grid.Col>
            <Grid.Col>8</Grid.Col>
            <Grid.Col>8</Grid.Col>
        </Grid>
        <Grid>
            <Grid.Col>6</Grid.Col>
            <Grid.Col>6</Grid.Col>
            <Grid.Col>6</Grid.Col>
            <Grid.Col>6</Grid.Col>
        </Grid>
        <Grid>
            <Grid.Col>4</Grid.Col>
            <Grid.Col>4</Grid.Col>
            <Grid.Col>4</Grid.Col>
            <Grid.Col>4</Grid.Col>
            <Grid.Col>4</Grid.Col>
            <Grid.Col>4</Grid.Col>
        </Grid>
        <Grid>
            <Grid.Col>2</Grid.Col>
            <Grid.Col>2</Grid.Col>
            <Grid.Col>2</Grid.Col>
            <Grid.Col>2</Grid.Col>
            <Grid.Col>2</Grid.Col>
            <Grid.Col>2</Grid.Col>
            <Grid.Col>2</Grid.Col>
            <Grid.Col>2</Grid.Col>
            <Grid.Col>2</Grid.Col>
            <Grid.Col>2</Grid.Col>
            <Grid.Col>2</Grid.Col>
            <Grid.Col>2</Grid.Col>
        </Grid>
        <Grid>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
            <Grid.Col>1</Grid.Col>
        </Grid>
    </div>
)
